# Generated by Django 5.0.6 on 2024-12-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.deck'),
            preserve_default=False,
        ),
    ]
