# Generated by Django 5.0.6 on 2025-01-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_deck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='last_studied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
